/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.jansel.feixiao

import dev.jansel.feixiao.extensions.EventHooks
import dev.jansel.feixiao.extensions.MessageEvents
import dev.jansel.feixiao.utils.*
import dev.kordex.core.ExtensibleBot

suspend fun main() {
	val bot = ExtensibleBot(token) {
		extensions {
			add(::MessageEvents)
			add(::EventHooks)
		}
	}
	bot.start()
}
