name: Build & Publish

on:
  push:
    branches:
      - root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Disable SSL verify (Temporary Fix)
        run: git config --global http.sslVerify false
        
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle (Build)
        run: "./gradlew build"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3

        with:
          registry: pi5:8125
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PW }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: pi5:8125/jansel/feixiao:latest
